Update database-credentials.sh
scorelab/Bassa pull request #331
Opened 2017-12-25 05:39 UTC by padamchopra

## Update database-credentials.sh
[GCI 2017]

This is a screenshot of the working script-
![bassacredentials](https://user-images.githubusercontent.com/19776024/34333539-ebb9cbda-e963-11e7-9570-e7d171dc984e.png)

**[The final config yml is stored in root folder and saved by the name bassa.yml]**

2017-12-25 14:42 UTC, agentmilindu commented on scripts/database-credentials.sh
> +read -p "Database password: " DBPASSWORD;
@padamchopra  I think we have to make the password hidden, like, when the user types the password on the terminal, it should not show the password typing. 

See: https://stackoverflow.com/a/3980904/1190184

2017-12-25 14:54 UTC, agentmilindu approved these changes
LGTM

2017-12-25 15:15 UTC, agentmilindu submitted a review, later dismissed
LGTM

2017-12-25 17:26 UTC, malithsen requested changes

2017-12-25 17:26 UTC, malithsen commented on scripts/database-credentials.sh
> +read -p "Database username: " DBUSERNAME;
Need some validation here, this cannot be empty.

2017-12-25 17:37 UTC, padamchopra commented
@malithsen I've made the changes. Empty inputs are not allowed.
![changedcredentials](https://user-images.githubusercontent.com/19776024/34341945-69f5b752-e9c8-11e7-9dc3-2e565ba8b32c.png)

2018-02-18 20:19 UTC, agentmilindu commented
@malithsen @rehrumesh Can we merge this PR?

2018-09-29 21:28 UTC, Sandhya023 approved these changes

2026-07-28 22:28 UTC, closed without merging